global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: book-share-api
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - booksharing-api:8081

  - job_name: cover-detection
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - cover-detection:8000
